books/urls.py
from django.urls import path
from . import views

app_name = 'books'

urlpatterns = [
    path('', views.book_list, name='book_list'),
    path('list/<int:pk>/', views.book_detail, name='detail'),
]

bookstore_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from sales.views import login_view, logout_view, register_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sales.urls')),
    path('books/', include('books.urls')),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register_view, name='register'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sales/urls.py
from django.urls import path
from .views import home, login_view, logout_view, records

app_name = 'sales'

urlpatterns = [
   path('', home, name='home'),  
   path('records/', records, name='records'),
   path('login/', login_view, name='login'),
   path('logout/', logout_view, name='logout'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>{% block title %}Bookstore{% endblock %}</title>

    <!-- Base CSS -->
    <link rel="stylesheet" href="{% static 'base.css' %}">

    {% block extra_head %}{% endblock %}
</head>

<body>

    <!-- NAVBAR -->
<nav class="navbar">
    <div class="navbar-left">
        <a href="{% url 'sales:home' %}" class="logo-link">
            <img src="{% static 'images/book_logo.png' %}" alt="BookNest Logo" class="logo">
        </a>
        <span class="brand">BookNest</span>
    </div>

   <div class="navbar-right">
        <a href="{% url 'sales:home' %}">Home</a>
        <a href="{% url 'sales:records' %}">Records</a>
        <a href="{% url 'books:book_list' %}">Books</a>

        {% if request.user.is_authenticated %}
            <a href="{% url 'logout' %}">Logout</a>
        {% else %}
            <a href="{% url 'sales:login' %}">Login</a>
        {% endif %}
    </div>
</nav>

    <!-- PAGE CONTENT -->
    <div class="container">
        {% block content %}{% endblock %}
    </div>

</body>
</html>